# Generated by roxygen2: do not edit by hand

# ---- Suppress 'no visible binding for global variable' notes ----
utils::globalVariables(c(
  ".", "association_score", "disease_name", "drug_name", "drug_type", "gene",
  "gene_count", "hgnc_symbol", "intersection", "mechanism_of_action", "p_value", "phase",
  "term_id", "term_name"
))
